jsf:
  PROJECT_STAGE: Production
joinfaces:
  version: @project.parent.version@
spring-boot:
  version: @project.parent.parent.version@
tomcat:
  version: @tomcat.version@
cdi:
  version: @cdi.version@
mojarra:
  version: @javax.faces.version@
omnifaces:
  version: @omnifaces.version@
security:
  ignored:
    - /javax.faces.resource/**